Module stack trace lines not parsed correctly Stack Traces Console #119
eclipse-jdt/eclipse.jdt.debug pull request #120
Opened 2022-09-13 09:24 UTC by trancexpress

This change adjusts the regexp used for Java stack trace lines in the Java Stack Traces Console, to include the symbol '@' which can be present in stack trace lines printed by jstack. E.g.:

at java.lang.String.join(java.base@11.0.10/String.java:2400)

In addition, JavaStackTraceHyperlink is adjusted to correctly identify the type in such stack trace lines.

Fixes: #119
Signed-off-by: Simeon Andreev <simeon.danailov.andreev@gmail.com>

## What it does

## How to test

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2022-09-14 12:56 UTC, iloveeclipse requested changes
LGTM in general, but pom file needs an update

2022-09-14 12:56 UTC, iloveeclipse commented on org.eclipse.jdt.debug.ui/META-INF/MANIFEST.MF
> +Bundle-Version: 3.12.900.qualifier
Simeon, please update pom.xml version too.

2022-09-14 12:58 UTC, iloveeclipse commented
Note: with this fix the lines are properly highlighted (OK), but I get a selection dialog (NOK) even if the choice is clear and unique (from human point of view). I will create another bug to follow up.

![image](https://user-images.githubusercontent.com/964108/190160138-9bbcb09f-a63e-441a-a414-5ca237c4e852.png)

2022-09-14 13:14 UTC, trancexpress commented
> Note: with this fix the lines are properly highlighted (OK), but I get a selection dialog (NOK) even if the choice is clear and unique (from human point of view). I will create another bug to follow up.

If the jar has some information about the version of the module, maybe we can get that to work. The file path of the jar having the version is coincidence.

2022-09-14 13:18 UTC, iloveeclipse commented
I was thinking about JDK classes first, because we know version from stsck trace and we know JDK version for module. I haven't checked if there is a JDT metadata for **any** module available, but for JDK  for sure.

2022-09-16 12:17 UTC, iloveeclipse commented
Tests on gerrir reproducibly hang, I've created #122.

2022-09-16 12:38 UTC, iloveeclipse commented
We have to wait until we have fixed SDK build, see https://github.com/eclipse-platform/eclipse.platform/pull/175

2022-09-19 09:49 UTC, iloveeclipse approved these changes

2022-09-19 10:02 UTC, iloveeclipse commented
Build doesn't work now because of next issue:
```
11:52:44  [INFO] --- tycho-p2-plugin:3.0.0-SNAPSHOT:p2-metadata-default (default-p2-metadata-default) @ org.eclipse.jdt.debug ---
11:52:44  [WARNING] MavenProject: org.eclipse.jdt:org.eclipse.jdt.debug:3.19.300-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse.jdt.debug-github_PR-120/org.eclipse.jdt.debug/pom.xml: baseline and build artifacts have same version but different contents
11:52:44     no-classifier: different
11:52:44  
11:52:44  [INFO] MavenProject: org.eclipse.jdt:org.eclipse.jdt.debug:3.19.300-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse.jdt.debug-github_PR-120/org.eclipse.jdt.debug/pom.xml
11:52:44      The main artifact has been replaced with the baseline version.
11:52:44      The following attached artifacts have been replaced with the baseline version: [sources]
11:52:44  
```

```
11:52:45  [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.debug: /tmp/zip12556784887552147557.zip -> [Help 1]
11:52:45  [ERROR] 
11:52:45  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
11:52:45  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
11:52:45  [ERROR] 
11:52:45  [ERROR] For more information about the errors and possible solutions, please read the following articles:
11:52:45  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
11:52:45  [ERROR] 
11:52:45  [ERROR] After correcting the problems, you can resume the build with the command
11:52:45  [ERROR]   mvn <args> -rf :org.eclipse.jdt.debug
```

OMG

2022-09-19 10:13 UTC, iloveeclipse commented
@vik-chand : any idea about the fail above? `org.eclipse.jdt.debug` wasn't touched at all in this PR.

2022-09-19 10:28 UTC, vik-chand commented
Added -e in jenkins file to see the stack trace for this error

2022-09-19 10:40 UTC, iloveeclipse commented
> Added -e in jenkins file to see the stack trace for this error

Still same, and "-e" is missing : 
```
12:29:04  + mvn clean verify --batch-mode --fail-at-end -Dmaven.repo.local=/home/jenkins/agent/workspace/eclipse.jdt.debug-github_PR-120/.m2/repository -Pbuild-individual-bundles -Pbree-libs -Papi-check -Dcompare-version-with-baselines.skip=false -Dproject.build.sourceEncoding=UTF-8 -DtrimStackTrace=false
12:29:04  Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
```

2022-09-19 11:00 UTC, sravanlakkimsetti commented
Hmm this is interesting
```
Loading trusted files from base branch master at ba10314cf4afe58f6bba9fbac05698047d9e25b1 rather than e286ac7b44f3c78d7340da50c49a5a12892be2e8
Obtained Jenkinsfile from ba10314cf4afe58f6bba9fbac05698047d9e25b1
‘Jenkinsfile’ has been modified in an untrusted revision
```

Basically what ever changes we made are not picked up

2022-09-19 11:03 UTC, iloveeclipse commented
> Basically what ever changes we made are not picked up

Could it be, the change should be done in dedicated PR by project committer?

2022-09-19 11:10 UTC, sravanlakkimsetti commented
> Could it be, the change should be done in dedicated PR by project committer?

I am creating another PR with those changes let see how it goes

2022-09-19 12:36 UTC, merged

2022-09-19 12:36 UTC, iloveeclipse commented
Hallelujah!