Ignore 'this' by checking the name of the variable
eclipse-jdt/eclipse.jdt.debug pull request #181
Opened 2023-01-27 11:41 UTC by nisargjhaveri

## What it does
Fix #179.
While getting the list of variables for a method, we were skipping the first slot assuming it was a reference to `this`. Though this is not always the case when testing with Android dex files. Instead of assuming `this` is at the first slot, check the name of the variable.

## How to test
Tested locally, the issue that was reported earlier no longer occurs.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-02-08 17:01 UTC, nisargjhaveri commented
@SarikaSinha, @iloveeclipse, Could you please have a look at this? Please let me know if this doesn't make sense or requires more changes.

2023-02-09 13:56 UTC, SarikaSinha commented
> @SarikaSinha, @iloveeclipse, Could you please have a look at this? Please let me know if this doesn't make sense or requires more changes.

I will be able to look at this not before next week.

2023-02-22 13:53 UTC, SarikaSinha commented
@nisargjhaveri 

Can you add some test like :
org.eclipse.debug.jdi.tests.MethodTest.testJDIVariablesByName()
org.eclipse.debug.jdi.tests.MethodTest.testJDIArguments()

2023-02-22 16:40 UTC, nisargjhaveri commented
@SarikaSinha, sure, I can add the required tests. Though, what should the new tests cover? The tests you mentioned along with `org.eclipse.debug.jdi.tests.MethodTest.testJDIVariables` seems to cover most cases I can think of.

2023-02-22 17:04 UTC, SarikaSinha commented
> @SarikaSinha, sure, I can add the required tests. Though, what should the new tests cover? The tests you mentioned along with `org.eclipse.debug.jdi.tests.MethodTest.testJDIVariables` seems to cover most cases I can think of.

It should cover the case of failure with the old code, which you have stated in the problem. And it should pass after the change ideally.

2023-02-22 18:11 UTC, nisargjhaveri commented
Okay, that way.. I believe the issue only repros in with the dex files compiled for Android. How should we go about writing tests for that? We'd need to compile to dex/APK first and then likely run Android Emulator to test?

2023-02-23 04:33 UTC, SarikaSinha commented
Yes, something like that. 
Problem in not adding the test is if someone later changes this logic, it might not work for dex files again.

2023-02-23 04:58 UTC, nisargjhaveri commented
Do we have any tests running on Android?

If not, adding the entire infra to run tests on Android would be a fairly complex work, especially for someone like me who's new to the project. While I completely agree with the fact that we should add tests for this, I don't really have enough context in this project yet. I'd be willing to take a look, but would require some more help in figuring out how to go about this.

2023-03-01 16:56 UTC, SarikaSinha commented
We don't have tests for Android. Is it possible to get the compiled classes from Android and just execute with the scenario?

2023-03-01 17:24 UTC, nisargjhaveri commented
I have attempted one POC for running tests on Android in #187. Have a look?

Android SDK provides the tool for compiling to a dex file, which runs on the dalvik vm. The Dalvik VM itself seems to be officially supported only on Android. There seems to be some ports available to run Dalvik directly on a linux machine and such, but could not find anything fully convincing. We can do some more research, if that works, makes the life much simpler.

In any case, if the current PR does not break any existing tests, can we go ahead with it and continue the discussion on the Android tests separately?

2023-03-03 11:27 UTC, SarikaSinha commented
Will release after 4.27 is complete.

2023-03-26 20:04 UTC, nisargjhaveri commented
@SarikaSinha, I believe 4.27 release should be complete now? Can we merge this now to make sure this goes into the next release?

2023-03-26 20:32 UTC, iloveeclipse requested changes
Just few formal recommendations for your PR
1) Please create dedicated branch for your changes and do not commit on master branch directly.
2) Please don't merge master brsnch into your branch to get latest master state
3) Please fetch from master and **rebase** your branch on latest master state
4) Please provide commit message that explains the fix and refers to original issue https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/179

2023-03-29 12:23 UTC, nisargjhaveri commented
@iloveeclipse, Thanks for your suggestions.

Yes, I agree having a dedicated branch helps, but changing it now would likely mean I'll have to create a new PR, losing the context. And I believe it would not matter much once merged?

I've taken in the other three recommendations and updated the branch, please have a look?

2023-03-29 12:36 UTC, iloveeclipse commented
> Yes, I agree having a dedicated branch helps, but changing it now would likely mean I'll have to create a new PR, losing the context. And I believe it would not matter much once merged?

It will. Please create new PR from dedicated branch. The context is https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/179 and it will not be lost.

2023-03-29 12:55 UTC, closed without merging