Shorten the long Configuration name
eclipse-jdt/eclipse.jdt.debug pull request #204
Opened 2023-03-20 16:58 UTC by Shee43

Fixes : #97 
@SarikaSinha

2023-03-20 20:40 UTC, iloveeclipse requested changes
Thanks for contributing.

Please look at the commit messages in git history of this repository and provide a proper commit message.

A good commit message should have short first sentence mentioning original issue on the first line and after a new lime longer explanation of the problem/solution. 

Also please add a "Fixes https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/97" line at the end of commit message.

2023-03-20 20:40 UTC, iloveeclipse commented on org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/ClasspathShortener.java
> +			String configName = (getLaunchConfigurationName().length() > 10) ? getLaunchConfigurationName().substring(0, 10)
1) Please extract getLaunchConfigurationName() to a variable
2) Please extract 10 to a constant

2023-03-20 20:43 UTC, iloveeclipse commented
Please also bump org.eclipse.jdt.launching bundle version to 3.19.1000 in manifest and pom.xml.

2023-04-12 18:32 UTC, SarikaSinha commented
In the favour of https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/232

2023-04-12 18:32 UTC, closed without merging