Store classpath files outside of workspace. Fixes #240
eclipse-jdt/eclipse.jdt.debug pull request #241
Opened 2023-04-20 10:10 UTC by diti0023

classpath files are stored below user's directory in order to have them accessible easily, for later usage and removal

## What it does
In the dialog Run Configurations, click on "Show Comandline". If there are many or long classpaths, they are collected in a file in order not to exceed the maximum command length (on a Linux system check with `getconf ARG_MAX`). This is also done for actually launching the run, but in that case these files are removed on terminating. When just showing the command line these files remain, in order to have them accessible later (i.e. after closing the dialog). In order not to fill up the workspace this change saves the files outside, below user's home directory.

## How to test

Create a project with many JAR files and long paths to them. When the command length of the OS is about to be exceeded, the resulting command changes from listing all files as parameters (-classpath) to a single entry like

`@/home/.../.temp-Main--module-path-arg-1681985065801.txt`

Up to now this file resides in the workspace; with this change it is located at `eclipse-temp` in user's home directory. 

## Author checklist

- [ x] I have thoroughly tested my changes
- [ x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

2023-04-20 12:45 UTC, diti0023 commented
unrelated test failure: SyntheticVariableTests.testCompleteMethodParameter_DeepInTwoNestedClasses

2023-04-20 13:01 UTC, iloveeclipse requested changes
I have not understood why storing in some home or temp directory is better as in the workspace, may be it can be explained better?

If my workspace is under /data/workspace/ and my home is under /home/some_user_name/ the solution here will make things worse, not better?

2023-04-20 13:53 UTC, diti0023 commented
> I have not understood why storing in some home or temp directory is better as in the workspace, may be it can be explained better?
> 
> If my workspace is under /data/workspace/ and my home is under /home/some_user_name/ the solution here will make things worse, not better?

The [original issue](https://github.com/eclipse-platform/eclipse.platform.debug/issues/84) complains about classpath files filling up the workspace, and there is a proposal to store these files outside the workspace. The home directory is the easiest to find on all OSes.

2023-04-20 14:02 UTC, diti0023 commented on org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/StandardVMRunner.java
> +		String homeDir = System.getProperty("user.home"); //$NON-NLS-1$
In the class ClasspathShortener there is a hint:

> The java.io.tmpdir should not be used on MacOs

As the files are not deleted they also hang forever in the workspace with the current solution. The dialog has no access to handle them, which IMO can be changed only with API changes.

2023-04-20 14:02 UTC, diti0023 commented on org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/StandardVMRunner.java
> +			tempOutputDir = null;
agreed

2023-04-20 14:20 UTC, iloveeclipse commented
> The https://github.com/eclipse-platform/eclipse.platform.debug/issues/84 complains about classpath files filling up the workspace, and there is a proposal to store these files outside the workspace

> The home directory is the easiest to find on all OSes.

Not always the easiest is the best :-)

Home can have quota set and can be on NFS. Temp files should go to temp directory, and it's again should be available on all OS'es

> In the class ClasspathShortener there is a hint:
> The java.io.tmpdir should not be used on MacOs

I see it is coming from https://bugs.eclipse.org/bugs/show_bug.cgi?id=385738 and I see I've missed to ask **why** as this comment was added.

So let us reiterate again:
- original issue was to shorten long classpath arguments
- the temp was **for whatever reason** not OK on Mac
- so CWD was used
- but one didn't provided a proper cleanup

So now you are trying to solve the problem by moving the directory around, which
- may again **for whatever reason** not work on Mac
- does not solve the cleanup issue

I think to avoid further regressions, let us to concentrate on a proper **cleanup**, not on moving directory ?

2023-04-21 09:25 UTC, diti0023 commented
switching to a different approach

2023-04-21 09:25 UTC, closed without merging