Use System Encoding for java command line argument files (fixes #45)
eclipse-jdt/eclipse.jdt.debug pull request #47
Opened 2022-05-11 13:07 UTC by jukzi

https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/45

2022-05-13 05:34 UTC, vogella commented
@jjohnstn can you review?

2022-05-13 16:13 UTC, jjohnstn requested changes

2022-05-13 16:13 UTC, jjohnstn commented on org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/ClasspathShortener.java
> +	static final Charset SYTEM_CHARSET = (System.getProperty("native.encoding") != null) // Populated on Java 18 and later //$NON-NLS-1$
typo: Should be SYSTEM_CHARSET

2022-05-13 20:31 UTC, jjohnstn approved these changes

2022-05-13 20:42 UTC, jjohnstn commented
@iloveeclipse I think this patch is fine and uses the suggested logic in the JEP documentation.  Since you were commenting on the original issue, I will ask if you have any other comments, otherwise, it can be merged.

2022-05-16 11:27 UTC, iloveeclipse commented
I'm not sure I can see any change with the PR. 

I've patched `org.eclipse.jdt.internal.launching.ClasspathShortener.getMaxCommandLineLength()` to return 42 on Windows  and see that the file is still generated with UTF-8 on Java 11 in `org.eclipse.jdt.internal.launching.ClasspathShortener.createClassPathArgumentFile(String)`.

Using Java 11 I can't launch the class, using Java 8 everything works.

Here is what I get from java 11 (java 17 similar)
```
Error: Could not find or load main class @D:\tmp\wsp411\JÃ¶rg\.temp-Joerg-classpath-arg-1652700414353.txt
Caused by: java.lang.ClassNotFoundException: @D:\tmp\wsp411\JÃ¶rg\.temp-Joerg-classpath-arg-1652700414353.txt
```

I'm missing something? Ideally we would have a test that shows the expected vs current behavior.

2022-05-16 11:30 UTC, iloveeclipse requested changes
See my comment on PR. I assume something is still missing, or at least a test that shows the change actually works as expected (might be I'm testing it wrong manually).

2022-05-16 11:34 UTC, iloveeclipse commented
Here my project which I've used to see what is working what is not: [pr_47.zip](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/8699643/pr_47.zip). I couldn't get it working on Java 11/17 on my (Windows 11) system in the workspace that reported UTF-8 as default encoding.

2022-05-16 17:57 UTC, jukzi commented
if you start eclipse with `-Dfile.encoding=UTF-8`  that parameter is also passed to launched configurations.
Charset.defaultCharset() then NOT returns the SYSTEM encoding but the UTF-8 encoding passed. 
1. that's seems to be against the specification
2. why does eclipse start with that  -Dfile.encoding=UTF-8 by default?
The encoding can be changed in the launch configuration but unfortunatly not to SYSTEM default.
![image](https://user-images.githubusercontent.com/51790620/168654023-22d302b7-badd-40be-8e24-63cee809827c.png)

2022-05-16 18:01 UTC, iloveeclipse commented
See https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/24

2022-05-16 19:08 UTC, jukzi commented
jdk uses "sun.jnu.encoding" for real System charset
https://github.com/openjdk/jdk/pull/8378/files#diff-f9ae2535b3ccc7376de825e468d3e5758c0f476436d6f326361eb57d103f7e5aR155

2022-05-30 10:56 UTC, jukzi commented
@iloveeclipse 
I changed to implementation that works even when -Dfile.encoding is set.
Also gives a reasonsanble error message if argument cannot be encoded:
![image](https://user-images.githubusercontent.com/51790620/170977833-04437778-4f44-48af-81a7-1441faba654e.png)

please review

2022-06-14 09:17 UTC, jukzi commented
ok, enjoy your vacation!!

2022-06-22 07:38 UTC, iloveeclipse commented on org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/ClasspathShortener.java
> +	static final Charset SYTEM_CHARSET = (System.getProperty("native.encoding") != null) // Populated on Java 18 and later //$NON-NLS-1$
[The PR with new API is merged](https://github.com/eclipse-platform/eclipse.platform/pull/38) and new API will be available after the next I-build.

2022-06-23 13:34 UTC, jukzi commented
ping @iloveeclipse

2022-07-25 08:23 UTC, jukzi commented
@iloveeclipse 
I think I covered all requested changes but still no review/submit, what do you think is missing?

2022-07-30 12:52 UTC, iloveeclipse approved these changes
LGTM

2022-07-30 12:54 UTC, merged